framework:
  website: tornadoweb.org
  version: 6.0
  
command: >
  gunicorn -c config.py \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class gunicorn.workers.gtornado.TornadoWorker \
      server:app
