providers:
  aws:
    version: 2.4
    user: ec2-user
    # amazon linux 2 use cloud-init 18.2
    config:
      runcmd:
        - amazon-linux-extras install ruby2.4
        - yum --assumeyes install ruby-devel
        - yum --assumeyes install @development
        - yum --assumeyes install rubygems
        - gem install bundler --no-ri --no-rdoc
        - gem install puma --no-ri --no-rdoc
  digitalocean:
    # cloud-init 17.1
    version: 2.5
    config:
      package_update: true
      package_upgrade: true
      packages:
        - ruby
        - ruby-devel
        - rubygems
        - "@development-tools"
        - "@rpm-development-tools"
        - "@c-development"
      runcmd:
        - systemctl enable web
        - gem install bundler --no-ri --no-rdoc
