language:
  version: 3.0

framework:
  environment:
    RACK_ENV: production

  files:
    - "**/*.rb"
    - config/*.yml
    - Gemfile
    - Rakefile
    - config.ru

  variants:
    puma: bundle exec puma -p 3000 -w $(nproc)
    falcon: bundle exec falcon serve --bind http://0.0.0.0:3000 --count $(nproc)
    iodine: bundle exec iodine -p 3000 -w $(nproc)
