providers:
  digitalocean:
    version: 2.5
    config:
      package_update: true
      package_upgrade: true
      packages:
        - ruby
        - ruby-dev
        - build-essential
      runcmd:
        - gem install bundler --no-ri --no-rdoc
        - sleep 1
