framework:
  github: dutradda/apidaora
  version: 0.26

deps:
  - libffi-devel
  - curl
  - openssl-devel
  
alpine-deps:
  - libffi-dev
  - curl
  - openssl-dev

boostratp:
  - curl https://sh.rustup.rs > init.sh
  - sh init.sh -y
  - rustup default nightly

files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  RUSTFLAGS: -C target-feature=-crt-static
  WORKER_CLASS: uvicorn.workers.UvicornWorker
  
