framework:
  github: dutradda/apidaora
  version: 0.27

build_deps:
  - libffi-dev
  - curl
  - openssl-dev

fixes:
  - curl https://sh.rustup.rs > init.sh
  - sh init.sh -y
  - find $HOME/.cargo/bin -type f -exec install {} /usr/local/bin \;
  - rustup default nightly

environment:
  RUSTFLAGS: -C target-feature=-crt-static
  
command: >
  gunicorn -c config.py \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class uvicorn.workers.UvicornWorker  \
      server:app
