framework:
  website: docs.microsoft.com/en-us/aspnet/index
  version: 3.0
  
files:
  - aspnetcore
  - aspnetcore.deps.json
  - aspnetcore.dll
  - aspnetcore.pdb
  - aspnetcore.runtimeconfig.json
  - web.config
