framework:
  website: hyperf.io
  version: 2.1

  bootstrap:
    - echo "swoole.use_shortname = 'Off'" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
    - php sbin/hyperf.php

  engines:
    swoole:
      extensions:
        - redis
        - swoole

      command: php sbin/hyperf.php start
