---
version: 2
updates:
- package-ecosystem: npm
  directory: "/javascript/moleculer"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/polka"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/foxify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/0http"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/sifrr"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/nestjs-fastify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fyrejet-api"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/restana"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/express"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/hapi"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/muneem"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/turbo_polka"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fyrejet-uwebsockets"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fyrejet"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/feathersjs"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/iotjs-express"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/nestjs-express"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/restify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/polkadot"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/rayo"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/naturaljs-router"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/sails"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fastify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/koa"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/."
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/syro"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/sinatra"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/rack_app"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/camping"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/roda"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/agoo"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/rack-routing"
  schedule:
    interval: daily
