---
version: 2
updates:
- package-ecosystem: npm
  directory: "/javascript/moleculer"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/polka"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/foxify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/0http"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/sifrr"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/nestjs-fastify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fyrejet-api"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/restana"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/express"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/hapi"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/muneem"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/turbo_polka"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fyrejet-uwebsockets"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fyrejet"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/feathersjs"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/iotjs-express"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/nestjs-express"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/restify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/polkadot"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/rayo"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/naturaljs-router"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/sails"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/fastify"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/javascript/koa"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/."
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/syro"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/sinatra"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/rack_app"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/camping"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/roda"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/agoo"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/rack-routing"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/hanami"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/flame"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/hanami-api"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/pakyow"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/grape"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/cuba"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/ruby/rails"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/rust/gotham"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/rust/iron"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/rust/nickel"
  schedule:
    interval: daily
- package-ecosystem: cargo
  directory: "/rust/actix"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/slim-swoole"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/chubbyphp-swoole"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/sunrise-router-roadrunner"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/slim-roadrunner"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/swoft"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/simps"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/nano"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/codeigniter4"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/yii"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/phalcon"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/one-fpm"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/ice"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/spiral"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/mark"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/siler-swoole"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/workerman"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/chubbyphp-roadrunner"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/nette"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/sw-fw-less"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/laminas"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/chubbyphp"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/imi"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/comet"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/sunrise-router"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/ubiquity"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/one"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/mezzio"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/lumen"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/siler"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/fastsitephp"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/bearframework"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/hamlet"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/symfony"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/slim"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/chubbyphp-workerman"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/sunrise-router-annotations"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/yii-swoole"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/laravel"
  schedule:
    interval: daily
- package-ecosystem: composer
  directory: "/php/hyperf"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/pony"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/go"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/nim"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/python"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/clojure"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/elixir"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/dart"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/perl"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/rust"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/fsharp"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/r"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/java"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/kotlin"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/crystal"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/haskell"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/php"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/scala"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/cpp"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/swift"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/csharp"
  schedule:
    interval: daily