framework:
  github: itsumura-h/nim-basolato
  version: 0.5

files:
  - /usr/src/app/server

deps:
  - openssh-client
  - openssl
  - pcre
  - pcre-dev
  - bsd-compat-headers

build_opts: '--define: usePcreHeader --passL: "/usr/lib/libpcre.a"'
