framework:
  github: itsumura-h/nim-basolato
  version: 0.8

files:
  - /usr/src/app/server

deps:
  - bsd-compat-headers

alpine-deps:
  - pcre-dev

build_opts: '--threadAnalysis:off --define: usePcreHeader --passL: "/usr/lib/libpcre.a"'
