framework:
  website: rapidoid.org
  version: 5.5

files: 
  - target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar

mvn_build: mvn compile assembly:single -q

command: >
  java -server
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts 
  -cp target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar
  benchmark.rapidoid.Main profiles=production
  
