# PHP Code Sniffer is not activated by default
# @see http://help.houndci.com/configuration/hound

phpcs:
  enabled: true

# Specify eslint config file
# @see https://intercom.help/hound/configuration/eslint
eslint:
  enabled: true
  config_file: .eslintrc.json