---

# Python

- enabled: true
  name: black
  image: restyled/restyler-black
  command:
    - black
  arguments: []
  include:
    - "**/*.py"
  interpreters:
    - python
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
    - https://github.com/python/black

# C / C++

- enabled: true
  name: clang-format
  image: restyled/restyler-clang-format
  command:
    - clang-format
    - "-i"
  arguments: []
  include:
    - "**/*.c"
    - "**/*.cc"
    - "**/*.cpp"
    - "**/*.h"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
    - https://clang.llvm.org/docs/ClangFormat.html

# Java

- enabled: true
  name: google-java-format
  image: restyled/restyler-google-java-format
  command:
    - google-java-format
    - "--replace"
  arguments: []
  include:
    - "**/*.java"
  interpreters: []
  supports_arg_sep: false
  supports_multiple_paths: true
  documentation:
    - https://github.com/google/google-java-format#readme

# PHP

- enabled: true
  name: php-cs-fixer
  image: restyled/restyler-php-cs-fixer
  command:
    - php-cs-fixer
    - fix
  arguments: []
  include:
    - "**/*.php"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: false
  documentation:
    - https://github.com/FriendsOfPHP/PHP-CS-Fixer

# JSON
 
- enabled: true
  name: prettier-json
  image: restyled/restyler-prettier
  command:
    - prettier
    - "--write"
  arguments: []
  include:
    - "**/*.json"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
    - https://prettier.io/docs/en/options.html#parser

# YAML config

- enabled: true
  name: prettier-yaml
  image: restyled/restyler-prettier
  command:
    - prettier
    - "--write"
  arguments: []
  include:
    - "**/*.yml"
    - "**/*.yaml"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
    - https://prettier.io/docs/en/
    - https://prettier.io/blog/2018/07/29/1.14.0.html

# Javascript
      
- enabled: true
  name: prettier
  image: restyled/restyler-prettier:v2.0.2-1
  command:
    - prettier
    - "--write"
  arguments: []
  include:
    - "**/*.js"
    - "**/*.jsx"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
    - https://prettier.io/docs/en/

# Ruby

- enabled: true
  name: rubocop
  image: restyled/restyler-rubocop
  command:
    - rubocop
    - "--auto-correct"
    - "--fail-level"
    - fatal
  arguments: []
  include:
    - "**/*.rb"
  interpreters:
    - ruby
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
    - https://rubocop.readthedocs.io/en/latest/

# Rust

- enabled: true
  name: rustfmt
  image: restyled/restyler-rustfmt
  command:
    - rustfmt
  arguments: []
  include:
    - "**/*.rs"
  interpreters: []
  supports_arg_sep: true
  supports_multiple_paths: true
  documentation:
    - https://github.com/rust-lang-nursery/rustfmt#readme
    - https://github.com/restyled-io/restyled.io/wiki/Common-Errors:-Rustfmt
