# Push the style fixes directly to the original PR
#
# This setting implies pull_requests: false for origin PRs, and has no effect on
# forked PRs (since we can't push to those).
#
auto: false

# Open Restyle PRs?
pull_requests: true

# Leave comments on the original PR linking to the Restyle PR?
comments: true

statuses:
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
  error: true           # Red if we encounter errors restyling

restylers:
  - name: ormolu
  - name: clang-format
    include:
    - "**/*.c"
    - "**/*.cc"
    - "**/*.h"
  - name: google-java-format
  - name: black
  - name: rubocop
  - name: rustfmt
  - name: php-cs-fixer
