# Push the style fixes directly to the original PR
#
# This setting implies pull_requests: false for origin PRs, and has no effect on
# forked PRs (since we can't push to those).
#
auto: false

# Open Restyle PRs?
pull_requests: true

# Leave comments on the original PR linking to the Restyle PR?
comments: true

statuses:
  differences: true     # Red when style differences are found
  no_differences: true  # Green when no differences are found
  error: true           # Red if we encounter errors restyling

restylers:
  - name: ormolu # Haskell
  - name: clang-format # C / C++
    include:
    - "**/*.c"
    - "**/*.cc"
    - "**/*.h"
  - name: google-java-format # Java
  - name: black # Python
  - name: rubocop # Ruby
  - name: rustfmt # Rust
  - name: php-cs-fixer # PHP
  - name: prettier # Javascript
  - name: prettier-json # JSON
  - name: prettier-yaml # YAML
  # Missing clojure
  # Missing crystal
  # Missing csharp
  # Missing dart
  # Missing elixir
  - name: fantomas
  # Missing go
  # Missing julia
  # Missing kotlin
  # Missing nim
  # Missing perl
  # Missing pony
  # Missing scala
  # Missing swift
