require:
 - rubocop-rake
 - rubocop-rspec
 
AllCops:
  NewCops: enable
    
Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Exclude: 
    - ruby/rack-routing/app/route_handler.rb

Metrics/BlockLength:
  Enabled: false

Rake/Desc:
  Enabled: false

Layout/LineLength:
  Enabled: false