require:
 - rubocop-rake
 - rubocop-rspec
 
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
    
Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Exclude: 
    - ruby/rack-routing/app/route_handler.rb

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false