Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# rack-routing use method name for route handling
Naming/AccessorMethodName:
  Exclude:
    - ruby/rack-routing/app/route_handler.rb