# Use crystal by default
language: crystal

jobs:
  include:
    - stage: lint
      script: bash .ci/lint.sh
      language: c
      env: LANGUAGE=c DIRECTORY=c
    - stage: lint
      script: bash .ci/lint.sh
      language: cpp
      env: LANGUAGE=cpp DIRECTORY=cpp
    - stage: lint
      script: bash .ci/lint.sh
      language: crystal
      env: LANGUAGE=crystal DIRECTORY=crystal
    - stage: lint
      script: bash .ci/lint.sh
      language: csharp
      env: LANGUAGE=csharp DIRECTORY=csharp
    - stage: lint
      script: bash .ci/lint.sh
      language: go
      env: LANGUAGE=go DIRECTORY=go
    - stage: lint
      script: bash .ci/lint.sh
      language: java
      env: LANGUAGE=java DIRECTORY=java
    - stage: lint
      script: bash .ci/lint.sh
      language: generic
      env: LANGUAGE=nim DIRECTORY=nim
    - stage: lint
      script: bash .ci/lint.sh
      language: node_js
      env: LANGUAGE=node DIRECTORY=node
    - stage: lint
      script: bash .ci/lint.sh
      os: osx
      language: objective-c
      env: LANGUAGE=objc DIRECTORY=objc
    - stage: lint
      script: bash .ci/lint.sh
      language: php
      env: LANGUAGE=php DIRECTORY=php
    - stage: lint
      script: bash .ci/lint.sh
      language: python
      env: LANGUAGE=python DIRECTORY=python
    - stage: lint
      script: bash .ci/lint.sh
      language: ruby
      env: LANGUAGE=ruby DIRECTORY=ruby
    - stage: lint
      script: bash .ci/lint.sh
      language: rust
      env: LANGUAGE=rust DIRECTORY=rust
    - stage: lint
      script: bash .ci/lint.sh
      language: scala
      env: LANGUAGE=scala DIRECTORY=scala
    - stage: lint
      script: bash .ci/lint.sh
      os: osx
      language: objective-c
      env: LANGUAGE=swift DIRECTORY=swift
    
    
    - stage
      env: FRAMEWORK=kore
      services: - docker
    - stage
      env: FRAMEWORK=agoo-c
      services: - docker
    - stage
      env: FRAMEWORK=cuba
      services: - docker
    - stage
      env: FRAMEWORK=rack-routing
      services: - docker
    - stage
      env: FRAMEWORK=sinatra
      services: - docker
    - stage
      env: FRAMEWORK=roda
      services: - docker
    - stage
      env: FRAMEWORK=agoo
      services: - docker
    - stage
      env: FRAMEWORK=flame
      services: - docker
    - stage
      env: FRAMEWORK=rails
      services: - docker
    - stage
      env: FRAMEWORK=hanami
      services: - docker
    - stage
      env: FRAMEWORK=evhtp
      services: - docker
    - stage
      env: FRAMEWORK=spring-boot
      services: - docker
    - stage
      env: FRAMEWORK=act
      services: - docker
    - stage
      env: FRAMEWORK=hapi
      services: - docker
    - stage
      env: FRAMEWORK=fastify
      services: - docker
    - stage
      env: FRAMEWORK=0http
      services: - docker
    - stage
      env: FRAMEWORK=muneem
      services: - docker
    - stage
      env: FRAMEWORK=rayo
      services: - docker
    - stage
      env: FRAMEWORK=koa
      services: - docker
    - stage
      env: FRAMEWORK=express
      services: - docker
    - stage
      env: FRAMEWORK=foxify
      services: - docker
    - stage
      env: FRAMEWORK=restify
      services: - docker
    - stage
      env: FRAMEWORK=turbo_polka
      services: - docker
    - stage
      env: FRAMEWORK=restana
      services: - docker
    - stage
      env: FRAMEWORK=polka
      services: - docker
    - stage
      env: FRAMEWORK=aspnetcore
      services: - docker
    - stage
      env: FRAMEWORK=raze
      services: - docker
    - stage
      env: FRAMEWORK=amber
      services: - docker
    - stage
      env: FRAMEWORK=lucky
      services: - docker
    - stage
      env: FRAMEWORK=spider-gazelle
      services: - docker
    - stage
      env: FRAMEWORK=router.cr
      services: - docker
    - stage
      env: FRAMEWORK=kemal
      services: - docker
    - stage
      env: FRAMEWORK=athena
      services: - docker
    - stage
      env: FRAMEWORK=orion
      services: - docker
    - stage
      env: FRAMEWORK=onyx
      services: - docker
    - stage
      env: FRAMEWORK=starlette
      services: - docker
    - stage
      env: FRAMEWORK=japronto
      services: - docker
    - stage
      env: FRAMEWORK=falcon
      services: - docker
    - stage
      env: FRAMEWORK=bottle
      services: - docker
    - stage
      env: FRAMEWORK=sanic
      services: - docker
    - stage
      env: FRAMEWORK=bocadillo
      services: - docker
    - stage
      env: FRAMEWORK=cyclone
      services: - docker
    - stage
      env: FRAMEWORK=responder
      services: - docker
    - stage
      env: FRAMEWORK=masonite
      services: - docker
    - stage
      env: FRAMEWORK=quart
      services: - docker
    - stage
      env: FRAMEWORK=fastapi
      services: - docker
    - stage
      env: FRAMEWORK=hug
      services: - docker
    - stage
      env: FRAMEWORK=molten
      services: - docker
    - stage
      env: FRAMEWORK=vibora
      services: - docker
    - stage
      env: FRAMEWORK=django
      services: - docker
    - stage
      env: FRAMEWORK=flask
      services: - docker
    - stage
      env: FRAMEWORK=tornado
      services: - docker
    - stage
      env: FRAMEWORK=aiohttp
      services: - docker
    - stage
      env: FRAMEWORK=nickel
      services: - docker
    - stage
      env: FRAMEWORK=actix-web
      services: - docker
    - stage
      env: FRAMEWORK=rocket
      services: - docker
    - stage
      env: FRAMEWORK=gotham
      services: - docker
    - stage
      env: FRAMEWORK=iron
      services: - docker
    - stage
      env: FRAMEWORK=http4s
      services: - docker
    - stage
      env: FRAMEWORK=akkahttp
      services: - docker
    - stage
      env: FRAMEWORK=slim
      services: - docker
    - stage
      env: FRAMEWORK=zend-expressive
      services: - docker
    - stage
      env: FRAMEWORK=lumen
      services: - docker
    - stage
      env: FRAMEWORK=laravel
      services: - docker
    - stage
      env: FRAMEWORK=zend-framework
      services: - docker
    - stage
      env: FRAMEWORK=symfony
      services: - docker
    - stage
      env: FRAMEWORK=vapor
      services: - docker
    - stage
      env: FRAMEWORK=kitura-nio
      services: - docker
    - stage
      env: FRAMEWORK=perfect
      services: - docker
    - stage
      env: FRAMEWORK=kitura
      services: - docker
    - stage
      env: FRAMEWORK=ktor
      services: - docker
    - stage
      env: FRAMEWORK=echo
      services: - docker
    - stage
      env: FRAMEWORK=gorouter
      services: - docker
    - stage
      env: FRAMEWORK=gf
      services: - docker
    - stage
      env: FRAMEWORK=beego
      services: - docker
    - stage
      env: FRAMEWORK=chi
      services: - docker
    - stage
      env: FRAMEWORK=gin
      services: - docker
    - stage
      env: FRAMEWORK=gorilla-mux
      services: - docker
    - stage
      env: FRAMEWORK=kami
      services: - docker
    - stage
      env: FRAMEWORK=violetear
      services: - docker
    - stage
      env: FRAMEWORK=fasthttprouter
      services: - docker
    - stage
      env: FRAMEWORK=jester
      services: - docker

notifications:
  email: false
