# Use latest ubuntu LTS (18.04)
dist: bionic

services:
  - docker # Use docker to containerize frameworks
  - postgresql # Use postgresql to store data

# This tool is written in crystal
language: crystal

env:
  global:
    - DATABASE_URL="postgresql://postgres@localhost/benchmark"
    - secure: SGIE6GVnMKtSlZQxGaQE3eyT8u/NNEO7Ftn5glELr2whmp6NnFHM3ysP3ZxB6oM/h0JWhtPSqE3F3qMbHruT6/aUWrVJTE4t23InGFTGvV81/eqJZQ9QhXzCWoyWQte/aFOPSvHEsK7WNPTGvh49+diYcNn+sZ8s6JeI535KbHw2Tc2DV4YaWkR1JU1oW4TI3c3MLvX02PLdntzvIcoYEbjTfop1No3V0lUvFVycE1c/Yryk0LN/oIDGOjhE3aPev7UKt2SLglFVf274VbF5e4ylllDhKV1VGHyxW0wOxYVryR9vQ2PAYKbfrDEypBNpFf2mRjnjaKizziMIVSeUXe8bPeV71EMC9UBuZAqF01/T9yJJ1yk8ESN/uFD6ix9/yB940r8uLp6E9bHtgwEOQ/bKd59dZ2mOF0WQJYGUQh5zvRTF861il2Pm37ivwKqgzxKthe9UFDXfJDzNNQE9h2LjK4vLm46HqN739fFvzgMK6KAdx+qA8WiNJYIGvNIEOTe6tawnkr6X21YHJv8Q2TbDAf2xdyLoHU7DQldRi0dlwPPZXOdJtaLLvpPhNuqRh92yM4up5+dTJVb1I84i1U8az7Z6806JGULU6kJHZJMKXTSrRGDplOsNWQnSlaA/b/yNrVqFEeZXhJXah/lfKR6tKawrG58B6Wvl/4Smskg=
    - secure: gHsBB10MqYxAVv3X1rj61wxkl3PVxM+6AYz/kQMULCTMBM/6z8XMHH1AJV2O3bC4ZyiPfKiKBo9TKlae0Eush/iw2VvyGP7ay01RrEBRlaevUp4M0nrem9TiKbJWBXC+sbUvI9fSNvdo5YYkKn6RQobzbbge9yAYnpwqlhpA78W5FaSnycIOzx21HYmZky8YVSYLslQPGL3UrOlhB37IQPSHNs3kvFXUcqC68y+/HoX2IziuV2qE9mCmYvigOeRl3F2vNwSKHn1VMqViK1eNOSXPJHFiq3Zi17+QIUsmp5UAHWhkHe+B66QEjwasXTARZbuMHAWab0uYKs/mWhs077n6LIuJncqS7Ae2e/2Ag7Ec2lmgq7Nyi82WvIa/ukRdBhnmXS0v6ojZMHWoELJHJVFxirIDiQcj+kkh3rAEqiSy35pGm/eXv9gNGhxiNyJ2YTGLT78zP+NSESXMAmo0fKiIUHpP2WmYvgBxcjGZTQfNyKD/a58CE0OpawSNjbplBd17NUud/sE5+Nb4S7/cRz8TCI+zCIkDnRC2WDolDImsdphOrQC+voNMnZrGOHx2eEY0+6R5vBTJ8UuC46fZag4ksoK7KEcoAnUVLN8VuwrxgOP4j3VlVYR8qJ7Vj3XPr+8LLfR4Hbt/80Ru0Xw4G9ofFNMPff2tZwS0mj74LdU=
  jobs:
      - FRAMEWORK=httpbeast
      - FRAMEWORK=jester
      - FRAMEWORK=phoon
      - FRAMEWORK=kore
      - FRAMEWORK=agoo-c
      - FRAMEWORK=coast
      - FRAMEWORK=cowboy_stream
      - FRAMEWORK=phoenix
      - FRAMEWORK=cowboy
      - FRAMEWORK=plug
      - FRAMEWORK=nickel
      - FRAMEWORK=iron
      - FRAMEWORK=gotham
      - FRAMEWORK=merly
      - FRAMEWORK=evhtp
      - FRAMEWORK=drogon
      - FRAMEWORK=kemal
      - FRAMEWORK=spider-gazelle
      - FRAMEWORK=router.cr
      - FRAMEWORK=amber
      - FRAMEWORK=athena
      - FRAMEWORK=grip
      - FRAMEWORK=raze
      - FRAMEWORK=onyx
      - FRAMEWORK=lucky
      - FRAMEWORK=orion
      - FRAMEWORK=toro
      - FRAMEWORK=rails
      - FRAMEWORK=grape
      - FRAMEWORK=flame
      - FRAMEWORK=agoo
      - FRAMEWORK=roda
      - FRAMEWORK=rack-routing
      - FRAMEWORK=syro
      - FRAMEWORK=sinatra
      - FRAMEWORK=camping
      - FRAMEWORK=plezi
      - FRAMEWORK=hanami
      - FRAMEWORK=cuba
      - FRAMEWORK=akkahttp
      - FRAMEWORK=http4s
      - FRAMEWORK=gramework
      - FRAMEWORK=fasthttprouter
      - FRAMEWORK=router
      - FRAMEWORK=gin
      - FRAMEWORK=echo
      - FRAMEWORK=aero
      - FRAMEWORK=webgo
      - FRAMEWORK=chi
      - FRAMEWORK=mars
      - FRAMEWORK=air
      - FRAMEWORK=gorouter
      - FRAMEWORK=kami
      - FRAMEWORK=fasthttp
      - FRAMEWORK=goroute
      - FRAMEWORK=atreugo
      - FRAMEWORK=gorilla-mux
      - FRAMEWORK=violetear
      - FRAMEWORK=rte
      - FRAMEWORK=gorouter-fasthttp
      - FRAMEWORK=fiber
      - FRAMEWORK=gf
      - FRAMEWORK=httprouter
      - FRAMEWORK=beego
      - FRAMEWORK=aspnetcore
      - FRAMEWORK=imi
      - FRAMEWORK=swoft
      - FRAMEWORK=laravel
      - FRAMEWORK=lumen
      - FRAMEWORK=slim
      - FRAMEWORK=hyperf
      - FRAMEWORK=one-fpm
      - FRAMEWORK=zend-framework
      - FRAMEWORK=phalcon
      - FRAMEWORK=zend-expressive
      - FRAMEWORK=one
      - FRAMEWORK=ubiquity
      - FRAMEWORK=sw-fw-less
      - FRAMEWORK=basicphp
      - FRAMEWORK=symfony
      - FRAMEWORK=spiral
      - FRAMEWORK=hamlet
      - FRAMEWORK=yii
      - FRAMEWORK=workerman
      - FRAMEWORK=cherrypy
      - FRAMEWORK=apidaora
      - FRAMEWORK=responder
      - FRAMEWORK=asgineer
      - FRAMEWORK=quart
      - FRAMEWORK=emmett
      - FRAMEWORK=hug
      - FRAMEWORK=pyramid
      - FRAMEWORK=blacksheep
      - FRAMEWORK=starlette
      - FRAMEWORK=clastic
      - FRAMEWORK=aiohttp
      - FRAMEWORK=falcon
      - FRAMEWORK=molten
      - FRAMEWORK=flask
      - FRAMEWORK=fastapi
      - FRAMEWORK=django
      - FRAMEWORK=klein
      - FRAMEWORK=sanic
      - FRAMEWORK=bottle
      - FRAMEWORK=masonite
      - FRAMEWORK=tornado
      - FRAMEWORK=cyclone
      - FRAMEWORK=nameko
      - FRAMEWORK=ktor
      - FRAMEWORK=micronaut
      - FRAMEWORK=rapidoid
      - FRAMEWORK=spring-framework
      - FRAMEWORK=act
      - FRAMEWORK=spring-boot
      - FRAMEWORK=javalin
      - FRAMEWORK=dancer2
      - FRAMEWORK=suave
      - FRAMEWORK=restana
      - FRAMEWORK=express
      - FRAMEWORK=muneem
      - FRAMEWORK=iotjs-express
      - FRAMEWORK=polka
      - FRAMEWORK=fastify
      - FRAMEWORK=nanoexpress
      - FRAMEWORK=turbo_polka
      - FRAMEWORK=foxify
      - FRAMEWORK=0http
      - FRAMEWORK=polkadot
      - FRAMEWORK=rayo
      - FRAMEWORK=koa
      - FRAMEWORK=moleculer
      - FRAMEWORK=hapi
      - FRAMEWORK=restify
      - FRAMEWORK=sifrr
      - FRAMEWORK=perfect
      - FRAMEWORK=vapor
      - FRAMEWORK=swifter
      - FRAMEWORK=kitura-nio
      - FRAMEWORK=kitura

before_script:
  - psql -c 'CREATE DATABASE benchmark;' -U postgres;
  - psql -U postgres -d benchmark < .ci/dump.sql

script:
  - shards install
  - shards build
  - bin/make config --without-sieger --keep
  - travis_wait 25 bin/neph ${FRAMEWORK} --mode=CI
  - crystal spec
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} 
  - docker tag ${FRAMEWORK} ${DOCKER_USERNAME}/${FRAMEWORK} 
  - docker push ${DOCKER_USERNAME}/${FRAMEWORK}

notifications:
  email: false
