# Exit build if not necessary
before_install:
  # if we are on PR and the current framework has not been modified
  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]] ; then bash .ci/has_to_run.sh || travis_terminate 0 ; fi

  # if we are on a bot branch and NOT on a PR
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == pyup* ]] ; then travis_terminate 0 ; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == renovate/* ]] ; then travis_terminate 0 ; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == dependabot/* ]] ; then travis_terminate 0 ; fi

# Use docker to containerize frameworks
services: docker

# This tool is written in crystal
language: crystal

# One build per framework
# ! This list list has to be updated manually !
env:
  matrix:
    - FRAMEWORK=aspnetcore
    - FRAMEWORK=akkahttp
    - FRAMEWORK=http4s
    - FRAMEWORK=evhtp
    - FRAMEWORK=slim
    - FRAMEWORK=symfony
    - FRAMEWORK=laravel
    - FRAMEWORK=lumen
    - FRAMEWORK=zend-expressive
    - FRAMEWORK=zend-framework
    - FRAMEWORK=tornado
    - FRAMEWORK=sanic
    - FRAMEWORK=japronto
    - FRAMEWORK=flask
    - FRAMEWORK=vibora
    - FRAMEWORK=django
    - FRAMEWORK=bottle
    - FRAMEWORK=aiohttp
    - FRAMEWORK=quart
    - FRAMEWORK=cyclone
    - FRAMEWORK=falcon
    - FRAMEWORK=starlette
    - FRAMEWORK=responder
    - FRAMEWORK=jester
    - FRAMEWORK=act
    - FRAMEWORK=rails
    - FRAMEWORK=rack-routing
    - FRAMEWORK=sinatra
    - FRAMEWORK=hanami
    - FRAMEWORK=roda
    - FRAMEWORK=agoo
    - FRAMEWORK=flame
    - FRAMEWORK=raze
    - FRAMEWORK=kemal
    - FRAMEWORK=spider-gazelle
    - FRAMEWORK=lucky
    - FRAMEWORK=amber
    - FRAMEWORK=router.cr
    - FRAMEWORK=onyx
    - FRAMEWORK=orion
    - FRAMEWORK=kitura
    - FRAMEWORK=perfect
    - FRAMEWORK=vapor
    - FRAMEWORK=gin
    - FRAMEWORK=fasthttprouter
    - FRAMEWORK=echo
    - FRAMEWORK=iris
    - FRAMEWORK=beego
    - FRAMEWORK=gf
    - FRAMEWORK=gorilla-mux
    - FRAMEWORK=chi
    - FRAMEWORK=muxie
    - FRAMEWORK=nickel
    - FRAMEWORK=actix-web
    - FRAMEWORK=gotham
    - FRAMEWORK=rocket
    - FRAMEWORK=iron
    - FRAMEWORK=restify
    - FRAMEWORK=express
    - FRAMEWORK=restana
    - FRAMEWORK=hapi
    - FRAMEWORK=fastify
    - FRAMEWORK=foxify
    - FRAMEWORK=koa
    - FRAMEWORK=polka
    - FRAMEWORK=rayo
    - FRAMEWORK=turbo_polka
    - FRAMEWORK=kore
    - FRAMEWORK=agoo-c
    - FRAMEWORK=muneem

# Lint yaml files in a specific jobs
jobs:
  include:
    - stage: lint
      script: bash .ci/lint.sh
      env: FRAMEWORK=rails

script:
  - shards build
  - bin/neph -v
  - bin/neph ${FRAMEWORK} --mode=CI --seq
  - crystal spec

notifications:
  email: false
