version: '3'
services:
  pg:
    image: postgres:12-alpine
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=benchmark
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - .ci/dump.sql:/srv/dump.sql
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
