version: '3'
services:
  pg:
    image: postgres:12-alpine
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=benchmark
    volumes:
      - .ci/dump.sql:/usr/src/db/dump.sql
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
