framework:
  website: coastonclojure.com
  version: 1.0

files:
  - "src/**/*.clj"
  - deps.edn

environment:
  COAST_ENV: prod

build:
  - mkdir classes && clj -e "(compile 'server)" && clojure -Auberjar --main-class server

binaries:
  - coast.jar

command: /usr/bin/java -jar /opt/web/coast.jar 3000
