provider:
  default:
    language: 14.15

files:
  - app.js
  - package.json
  - ../.config/ecosystem.config.js

environment:
  NODE_ENV: production
  PORT: 3000
  PM2_HOME: /opt/web

bootstrap:
  - npm install
  - npm -g install pm2

deps:
  - "@development-tools"
  - nodejs

command: /usr/local/bin/pm2-runtime /opt/web/config/ecosystem.config.js app
