framework:
  website: hug.rest
  version: 2.6

command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    -k tornado \
      server:__hug_wsgi__
