framework:
  website: symfony.com
  version: 5.2

  engines:
    - php-fpm

  bootstrap:
    - mkdir -p var/log && chown www-data var/log
    - mkdir -p var/cache && chown www-data var/cache
    - php bin/console cache:warmup --no-debug
