framework:
  github: ohler55/agoo-c
  version: 2.14

provider:
  default:
    language: 11

download:
  - git clone -b v0.7.3 https://github.com/ohler55/agoo-c
  - cd agoo-c/src && make

sources:
  - Makefile
  - simple.c

build:
  - make

binaries:
  - simple

command: /opt/web/simple
