framework:
  website: quarkus.io
  version: 1.10

build:
  - mvn clean package -Dquarkus.package.type=uber-jar -Pnative

binaries:
  - target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar