[deps]
Merly = "5b70daea-9db9-5a46-aedf-2142e553ecc5"

[compat]
Merly = "0.2.1"

#Version specifier format
#Similar to other package managers, the Julia package manager respects semantic versioning (semver). As an example, a version specifier given as e.g. 1.2.3 is therefore assumed to be compatible with the versions [1.2.3 - 2.0.0) where ) is a non-inclusive upper bound. More specifically, a version specifier is either given as a caret specifier, e.g. ^1.2.3 or as a tilde specifier, e.g. ~1.2.3. Caret specifiers are the default and hence 1.2.3 == ^1.2.3. The difference between a caret and tilde is described in the next section. The union of multiple version specifiers can be formed by comma separating individual version specifiers, e.g.

#[compat]
#Example = "1.2, 2"
#will result in [1.2.0, 3.0.0).

#Caret specifiers
#A caret specifier allows upgrade that would be compatible according to semver. An updated dependency is considered compatible if the new version does not modify the left-most non zero digit in the version specifier.

#Some examples are shown below.

#[compat]
#PkgA = "^1.2.3" # [1.2.3, 2.0.0)
#PkgB = "^1.2"   # [1.2.0, 2.0.0)
#PkgC = "^1"     # [1.0.0, 2.0.0)
#PkgD = "^0.2.3" # [0.2.3, 0.3.0)
#PkgE = "^0.0.3" # [0.0.3, 0.0.4)
#PkgF = "^0.0"   # [0.0.0, 0.1.0)
#PkgG = "^0"     # [0.0.0, 1.0.0)
#While the semver specification says that all versions with a major version of 0 are incompatible with each other, we have made that choice that a version given as 0.a.b is considered compatible with 0.a.c if a != 0 and c >= b.

#Tilde specifiers
#A tilde specifier provides more limited upgrade possibilities. When specifying major, minor and patch versions, or when specifying major and minor versions, only the patch version is allowed to change. If you only specify a major version, then both minor and patch versions are allowed to be upgraded (~1 is thus equivalent to ^1). For example:

#[compat]
#PkgA = "~1.2.3" # [1.2.3, 1.3.0)
#PkgB = "~1.2"   # [1.2.0, 1.3.0)
#PkgC = "~1"     # [1.0.0, 2.0.0)
#PkgD = "~0.2.3" # [0.2.3, 0.3.0)
#PkgE = "~0.0.3" # [0.0.3, 0.0.4)
#PkgF = "~0.0"   # [0.0.0, 0.1.0)
#PkgG = "~0"     # [0.0.0, 1.0.0)
#For all versions with a major version of 0 the tilde and caret specifiers are equivalent.

#Inequality specifiers
#Inequalities can also be used to specify version ranges:

#[compat]
#PkgA = ">= 1.2.3" # [1.2.3,  ∞)
#PkgB = "≥ 1.2.3"  # [1.2.3,  ∞)
#PkgC = "= 1.2.3"  # [1.2.3, 1.2.3]
#PkgD = "< 1.2.3"  # [0.0.0, 1.2.2]
