framework:
  website: pgjones.gitlab.io/quart
  version: 0.13

command: >
  gunicorn -c config.py \
    --bind 0.0.0.0:3000 \
    --reuse-port \
    --workers $(nproc) \
    --worker-class uvicorn.workers.UvicornWorker \
      server:app
