framework:
  website: iceframework.org
  version: 1.5

  deps:
    - bash

nginx_conf:
  - |
    location /{\n\
        rewrite ^/(.*)$ /index.php?_url=/$1 last;\n\
    }\n\
  - |
    location = /index.php {\n\
      fastcgi_pass unix:/var/run/php-fpm.sock;\n\
      fastcgi_param   SCRIPT_FILENAME         $document_root/index.php;\n\
      include fastcgi_params;\n\
    }\n\

language:
  bootstrap:
    - wget -O /tmp/framework-1.5.1.tar.gz https://github.com/ice/framework/archive/1.5.1.tar.gz
    - cd /tmp/ && tar -xzf framework-1.5.1.tar.gz && cd framework-1.5.1 && bash install
    - echo "extension=ice.so" >> /usr/local/etc/php/conf.d/docker-php-ext-ice.ini
    - curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-dev --prefer-dist --classmap-authoritative
    - composer dumpautoload -o
