framework:
  website: playframework.com
  version: 2.8

files:
  - src/main/resources/application.conf
  - src/main/resources/routes

command: web-frameworks-play-0.1.0-SNAPSHOT/bin/web-frameworks-play
