files:
  - composer.json
  - public/index.php
  - bootstrap/app.php
  - app/User.php
  - app/Providers/AuthServiceProvider.php
  - app/Providers/AppServiceProvider.php
  - app/Providers/RouteServiceProvider.php
  - app/Providers/EventServiceProvider.php
  - app/Providers/BroadcastServiceProvider.php
  - app/Console/Kernel.php
  - app/Http/Kernel.php
  - app/Http/Middleware/EncryptCookies.php
  - app/Http/Middleware/TrimStrings.php
  - app/Http/Middleware/VerifyCsrfToken.php
  - app/Http/Middleware/TrustProxies.php
  - app/Http/Middleware/RedirectIfAuthenticated.php
  - app/Http/Controllers/Auth/ResetPasswordController.php
  - app/Http/Controllers/Auth/LoginController.php
  - app/Http/Controllers/Auth/ForgotPasswordController.php
  - app/Http/Controllers/Auth/RegisterController.php
  - app/Http/Controllers/Controller.php
  - app/Exceptions/Handler.php
  - routes/console.php
  - routes/api.php
  - routes/channels.php
  - routes/web.php
  - config/queue.php
  - config/hashing.php
  - config/cache.php
  - config/logging.php
  - config/mail.php
  - config/session.php
  - config/filesystems.php
  - config/auth.php
  - config/services.php
  - config/broadcasting.php
  - config/view.php
  - config/app.php
  - config/database.php
