files:
  - composer.json
  - public/index.php
  - bootstrap/app.php
  - php/laravel/app/User.php
  - php/laravel/app/Providers/AuthServiceProvider.php
  - php/laravel/app/Providers/AppServiceProvider.php
  - php/laravel/app/Providers/RouteServiceProvider.php
  - php/laravel/app/Providers/EventServiceProvider.php
  - php/laravel/app/Providers/BroadcastServiceProvider.php
  - php/laravel/app/Console/Kernel.php
  - php/laravel/app/Http/Kernel.php
  - php/laravel/app/Http/Middleware/EncryptCookies.php
  - php/laravel/app/Http/Middleware/TrimStrings.php
  - php/laravel/app/Http/Middleware/VerifyCsrfToken.php
  - php/laravel/app/Http/Middleware/TrustProxies.php
  - php/laravel/app/Http/Middleware/RedirectIfAuthenticated.php
  - php/laravel/app/Http/Controllers/Auth/ResetPasswordController.php
  - php/laravel/app/Http/Controllers/Auth/LoginController.php
  - php/laravel/app/Http/Controllers/Auth/ForgotPasswordController.php
  - php/laravel/app/Http/Controllers/Auth/RegisterController.php
  - php/laravel/app/Http/Controllers/Controller.php
  - php/laravel/app/Exceptions/Handler.php
  - php/laravel/routes/console.php
  - php/laravel/routes/api.php
  - php/laravel/routes/channels.php
  - php/laravel/routes/web.php
  - php/laravel/config/queue.php
  - php/laravel/config/hashing.php
  - php/laravel/config/cache.php
  - php/laravel/config/logging.php
  - php/laravel/config/mail.php
  - php/laravel/config/session.php
  - php/laravel/config/filesystems.php
  - php/laravel/config/auth.php
  - php/laravel/config/services.php
  - php/laravel/config/broadcasting.php
  - php/laravel/config/view.php
  - php/laravel/config/app.php
  - php/laravel/config/database.php
