framework:
  website: laravel.com
  version: 8.33

  environment:
    APP_ENV: production
    APP_DEBUG: false
    APP_KEY: base64:txfHNf/SOo222Rm8I39Urb9SmvUy+nuAF98t/ukF0lk=

  bootstrap:
    - mkdir bootstrap/cache
    - mkdir storage/framework/sessions -p
    - mkdir storage/framework/views -p
    - mkdir storage/framework/cache -p

    - chown -R www-data:www-data /usr/src/app
    - find /usr/src/app -type f -exec chmod 644 {} \;
    - find /usr/src/app -type d -exec chmod 755 {} \;
    - chmod -R ug+rwx storage /usr/src/app/bootstrap/cache

    - php artisan config:cache
    - php artisan route:cache

  build_deps:
    - libevent-dev

  modules:
    - pcntl
    - posix
    - sockets
    
  extensions:
    - event

  extensions_fix:
    - rm -fr /usr/local/etc/php/conf.d/docker-php-ext-event.ini
    - echo 'extension=event.so' >> /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini

  engines:
    workerman:
      command: php artisan servel start
