framework:
  website: http4s.org
  version: 0.18

files:
  - target/scala-2.12/http4s-assembly-0.0.1-SNAPSHOT.jar

command: java -jar /usr/src/app/target/scala-2.12/http4s-assembly-0.0.1-SNAPSHOT.jar
