framework:
  website: kore.io
  version: 3.3

provider:
  default:
    language: 99

clone:
  - wget -c https://kore.io/releases/kore-3.3.1.tar.gz && tar xvf kore-3.3.1.tar.gz
  - cd kore-3.3.1 && TASKS=1 NOTLS=1 make && make install

build:
  - cd hello && kodev build

bin_deps:
  - libssl1.1 

files:
  - ../../local/bin/kore
  - hello/conf/hello.conf
  - hello/hello.so

command: cd /usr/bin/hello && /local/bin/kore -f -n -r -c conf/hello.conf