framework:
  website: kore.io
  version: 3.3

provider:
  default:
    language: 99

sources:
  - "**/*.c"
  - "**/*.conf"

files:
  - "**/hello.conf"

download:
  - git clone -b 3.3.1-release https://github.com/jorisvink/kore kore-3.3.1-release
  - cd kore-3.3.1-release && TASKS=1 NOTLS=1 make && make install

build:
  - cd hello && kodev build
  - mv /usr/local/bin/kore kore
  - mv hello/hello.so .

build_deps:
  - libssl-dev

bin_deps:
  - openssl

binaries:
  - kore
  - hello.so

command: /opt/web/kore -f -n -r -c /opt/web/hello/conf/hello.conf
