framework:
  website: kore.io
  version: 4.0

provider:
  default:
    language: 99

sources:
  - "**/*.c"
  - "**/*.conf"

files:
  - "**/hello.conf"

download:
  - wget -c https://kore.io/releases/kore-4.0.1.tar.gz
  - tar -xvf kore-4.0.1.tar.gz
  - cd kore-4.0.1 && TASKS=1 NOTLS=1 make && make install

build:
  - cd hello && kodev build
  - mv /usr/local/bin/kore kore
  - mv hello/hello.so .

build_deps:
  - bsd-compat-headers
  - libressl-dev
  - audit-dev

bin_deps:
  - libressl

binaries:
  - kore
  - hello.so

command: /opt/web/kore -f -n -r -c /opt/web/hello/conf/hello.conf
