framework:
  website: kore.io
  version: 3.3

provider:
  default:
    language: 99
    
sources:
  - "**/*.c"
  - "**/*.conf"

download:
  - wget -c https://github.com/jorisvink/kore/archive/3.3.1-release.tar.gz && tar xvf 3.3.1-release.tar.gz
  - cd kore-3.3.1-release && TASKS=1 NOTLS=1 make && make install

build:
  - cd hello && kodev build

build_deps:
  - bsd-compat-headers
  - libressl-dev

bin_deps:
  - libressl

binaries:
  - ../../local/bin/kore
  - hello/hello.so

<<<<<<< HEAD
command: cd /usr/bin/hello && /local/bin/kore -f -n -r -c conf/hello.conf
=======
command: cd hello && /local/bin/kore -f -n -r -c conf/hello.conf
>>>>>>> 90838a2f... fix(c): Use multi-stage docker
