framework:
  github: an-tao/drogon
  version: 1.3

provider:
  default:
    language: 14/17

build_deps:
  - jsoncpp-dev
  - util-linux-dev
  - libressl-dev
  - zlib-dev
  - brotli-dev

bin_deps:
  - jsoncpp
  - libuuid
  - libressl
  - zlib
  - brotli

deps:
  - jsoncpp
  - openssl
  - zlib
  - uuid

binaries:
  - build/drogon_benchmark

download:
  - git clone --branch v1.3.0 https://github.com/an-tao/drogon
  - cd drogon && git submodule update --init

build:
  - mkdir build
  - cd build && cmake -DCMAKE_BUILD_TYPE=release ..
  - cd build && make

files:
  - config.json

command: /opt/web/build/drogon_benchmark /opt/web/config.json
