[package]
name = "server"
version = "0.1.0"
authors = ["Isaac Whitfield <iw@whitfin.io>"]

[dependencies]
gotham = "~0.4"
gotham_derive = "*"
hyper = "0.13"
serde = "*"
serde_derive = "*"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
incremental = false
