framework:
  website: codeigniter.com
  version: 4.1

  modules:
    - curl
    - intl
    - json
    - mbstring

  environment:
    CI_ENVIRONMENT: production

  bootstrap:
    - mkdir writable/cache -p
    - chown -R www-data:www-data writable/cache
