framework:
  website: codeigniter.com
  version: 4.0

php_mod:
  - curl
  - intl
  - json
  - mbstring

alpine-deps:
  - curl-dev
  - icu-dev
  - oniguruma-dev

deps:
  - php
  - composer
  - "@development-tools"
  - php-pear
  - php-devel
  - libicu-devel
  - libcurl-devel
  - oniguruma-devel

files:
  - "**/*.php"
  - composer.json
  - ../.config/nginx.conf

environment:
  CI_ENVIRONMENT: production

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  - mv config/nginx.conf /etc/nginx/conf.d/default.conf
  - sed -i 's/;prefix.*/prefix = \/opt\/web\/public/g' /etc/php-fpm.d/www.conf
  - "[[ -f /etc/fedora-release ]] && systemctl enable php-fpm || true"
  - "[[ -f /etc/fedora-release ]] && systemctl enable nginx || true"

  - mkdir writable/cache -p
  - chown -R www-data:www-data writable/cache
