framework:
  github: jatofg/nawa
  version: 0.6

build_deps:
  - boost-dev
  - openssl-dev
  - doxygen
  - graphviz
  - curl-dev
  - argon2-dev

bin_deps:
  - curl
  - boost
  - openssl
  - argon2

binaries:
  - build/nawa_benchmark

download:
  - git clone --branch v0.6.1 https://github.com/jatofg/nawa
  - cd nawa && git submodule update --init

build:
  - mkdir build
  - cd build && cmake -DCMAKE_BUILD_TYPE=release ..
  - cd build && make

files:
  - config.ini

command: /opt/web/build/nawa_benchmark /opt/web/config.ini
