framework:
  website: falconframework.org
  version: 2.0
  
command: >
  gunicorn -c config.py \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class meinheld.gmeinheld.MeinheldWorker \
      server:app