provider:
  default:
    language: 8
  digitalocean:
    language: 8

sources:
  - "**/*.java"
  - "**/*.properties"
  - "**/*.xml"

binaries:
  - target/*.jar

deps:
  - java-1.8.0-openjdk

alpine-deps:
  - jetty-runner
