framework:
  github: georgeu2000/rack-routing
  version: 0.0

  files:
    - Gemfile
    - config.ru
    - app/*.rb
    - config/routes.txt

  variants:
    puma:
      command: bundle exec puma -p 3000 -w $(nproc)
    falcon:
      command: bundle exec falcon serve --bind http://0.0.0.0:3000 --count $(nproc)
    iodine:
      command: bundle exec iodine -p 3000 -w $(nproc)
