framework:
  github: nanoexpress/nanoexpress
  version: 3.2

  engines:
    - uwebsockets

  environment:
    EXPERIMENTAL_FASTCALL: 1

  fixes:
    - ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
