framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

fixes:
  - mkdir -p /usr/share/java
  - apt-get -y update && apt-get -y install wget
  - wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.30.v20200611/jetty-runner-9.4.30.v20200611.jar -O /usr/share/java/jetty-runner.jar

files:
  - target/struts2-1.0.war

command: java  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts  -jar /usr/share/java/jetty-runner.jar --port 3000 target/struts2-1.0.war
