framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

binaries:
  - target/struts2-1.0.war
  - target/struts2-1.0/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/struts2-1.0/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar --port 3000 /opt/web/target/struts2-1.0.war
