framework:
  website: luminusweb.com
  version: 3.98

image: clojure:openjdk-11-lein-slim-buster

build:
  - lein uberjar

binaries:
  - target/uberjar/luminus.jar

command: java -jar target/uberjar/luminus.jar 3000
