providers:
  digitalocean:
    version: 1.30
    config:

      # Update distibution

      package_update: true
      package_upgrade: true

      # Write systemd config file

      write_files:
        - path: /lib/systemd/system/web.service
          permission: 0644
          content: |
            [Unit]
            Description=web
            After=network.target

            [Service]
            Type=simple
            WorkingDirectory=/usr/src/app
            ExecStart=/usr/src/app/server

            # customize limit for this service only
            # @see https://unix.stackexchange.com/questions/345595/how-to-set-ulimits-on-service-with-systemd
            LimitNOFILE=65536

            [Install]
            WantedBy=multi-user.target


      runcmd:

        # Reload systemd config
        - systemctl daemon-reload

         # Disable cloud-init
        - systemctl disable cloud-init

        # Enable created service at startup 
        - systemctl start web
<<<<<<< HEAD
        - systemctl enable web
=======
        - systemctl enable web
>>>>>>> add rust challengers
