providers:
  digitalocean:
    version: 8.11
    config:
      package_update: true
      package_upgrade: true
      packages:
        - nodejs
      runcmd:
        - curl -sL https://rpm.nodesource.com/setup_10.x > /tmp/setup.sh
        - bash /tmp/setup.sh
        - rm -fr /tmp/setup.sh
        - apt-get install -y nodejs
        - npm -g install pm2