providers:
  digitalocean:
    version: 8.11
    config:
      package_update: true
      package_upgrade: true
      packages:
        - nodejs
        - npm
      runcmd:
        - npm -g install pm2