framework:
  website: djangoproject.com
  version: 3.1

command: >
  gunicorn  \
    --log-level warning  \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    -k tornado  \
      app.wsgi
