framework:
  website: djangoproject.com
  version: 3.0

command: >
  gunicorn -c config.py \
    --bind 0.0.0.0:3000  \
    --reuse-port  \
    --workers $(nproc)  \
    --worker-class meinheld.gmeinheld.MeinheldWorker  \
      app.wsgi
