---
version: 1
update_configs:
- package_manager: rust:cargo
  update_schedule: live
  directory: rust/nickel
  default_labels:
  - language:rust
- package_manager: docker
  update_schedule: daily
  directory: rust
  default_labels:
  - language:rust
- package_manager: rust:cargo
  update_schedule: live
  directory: rust/iron
  default_labels:
  - language:rust
- package_manager: docker
  update_schedule: daily
  directory: rust
  default_labels:
  - language:rust
- package_manager: rust:cargo
  update_schedule: live
  directory: rust/gotham
  default_labels:
  - language:rust
- package_manager: docker
  update_schedule: daily
  directory: rust
  default_labels:
  - language:rust
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/rails
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/grape
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/flame
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/agoo
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/roda
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/rack-routing
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/syro
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/sinatra
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/camping
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/plezi
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/hanami
  default_labels:
  - language:ruby
- package_manager: ruby:bundler
  update_schedule: live
  directory: ruby/cuba
  default_labels:
  - language:ruby
- package_manager: go:modules
  update_schedule: daily
  directory: go/gramework
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/fiber
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/fasthttprouter
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/router
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/gin
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/echo
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/aero
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/webgo
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/chi
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/mars
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/air
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/gorouter
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/kami
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/fasthttp
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/goroute
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/atreugo
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/gorilla-mux
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/violetear
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/rte
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/gorouter-fasthttp
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/gf
  default_labels:
  - language:go
- package_manager: go:modules
  update_schedule: daily
  directory: go/beego
  default_labels:
  - language:go
- package_manager: php:composer
  update_schedule: live
  directory: php/imi
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/swoft
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/laravel
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/lumen
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/slim
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/hyperf
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/one-fpm
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/zend-framework
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/phalcon
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/zend-expressive
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/one
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/ubiquity
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/sw-fw-less
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/symfony
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/spiral
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/hamlet
  default_labels:
  - language:php
- package_manager: php:composer
  update_schedule: live
  directory: php/workerman
  default_labels:
  - language:php
- package_manager: python
  update_schedule: live
  directory: python/cherrypy
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/responder
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/asgineer
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/quart
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/hug
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/pyramid
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/blacksheep
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/starlette
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/clastic
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/aiohttp
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/falcon
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/molten
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/flask
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/fastapi
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/django
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/klein
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/bocadillo
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/sanic
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/bottle
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/masonite
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/tornado
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/cyclone
  default_labels:
  - language:python
- package_manager: python
  update_schedule: live
  directory: python/nameko
  default_labels:
  - language:python
- package_manager: java:gradle
  update_schedule: daily
  directory: java/micronaut
  default_labels:
  - language:java
- package_manager: java:maven
  update_schedule: daily
  directory: java/rapidoid
  default_labels:
  - language:java
- package_manager: java:maven
  update_schedule: daily
  directory: java/spring-framework
  default_labels:
  - language:java
- package_manager: java:maven
  update_schedule: daily
  directory: java/act
  default_labels:
  - language:java
- package_manager: java:maven
  update_schedule: daily
  directory: java/spring-boot
  default_labels:
  - language:java
- package_manager: java:maven
  update_schedule: daily
  directory: java/javalin
  default_labels:
  - language:java
- package_manager: javascript
  update_schedule: live
  directory: javascript/restana
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/express
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/muneem
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/iotjs-express
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/polka
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/nanoexpress-pro
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/fastify
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/nanoexpress
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/turbo_polka
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/foxify
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/0http
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/polkadot
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/rayo
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/koa
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/moleculer
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/hapi
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/restify
  default_labels:
  - language:javascript
- package_manager: javascript
  update_schedule: live
  directory: javascript/sifrr
  default_labels:
  - language:javascript
