languages:
  ruby:
    Gemfile:
      label: ruby:bundler
      update_schedule: live
  javascript:
    package.json:
      label: javascript
      update_schedule: live
  python:
    requirements.txt:
      label: python
      update_schedule: live
  php:
    composer.json:
      label: php:composer
      update_schedule: live
  elixir:
    mix.exs:
      label: elixir:hex
      update_schedule: live
  rust:
    Cargo.toml:
      label: rust:cargo
      update_schedule: live
  java:
    pom.xml:
      label: java:maven
      update_schedule: daily
    build.gradle:
      label: java:gradle
      update_schedule: daily
  go:
    go.mod:
      label: go:modules
      update_schedule: daily