framework:
  website: spring.io/projects/spring-framework
  version: 5.3

build:
  - mvn clean package

binaries:
  - target/benchmark-1.0.0.war
  - target/benchmark-1.0.0/WEB-INF/lib/jetty-runner-9.4.34.v20201102.jar

command: >
  java 
  -XX:+UseNUMA -XX:+UseParallelGC 
  -jar target/benchmark-1.0.0/WEB-INF/lib/jetty-runner-9.4.34.v20201102.jar --port 3000 target/benchmark-1.0.0.war
