[package]
name = "server"
version = "0.1.0"
authors = ["Kilian Koeltzsch <me@kilian.io>"]

[dependencies]
rocket = "0.4.0"
rocket_codegen = "0.3.9"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
