framework:
  website: nestjs.com
  version: 7.6

files:
  - nest-cli.json
  - src
  - tsconfig.build.json
  - tsconfig.json

bootstrap:
  - npm -g install pm2
  - npm install
  - npm -g install @nestjs/cli
  - nest build

command: pm2-runtime start dist/app.js -i $(nproc)
