framework:
  website: http://lets-blade.com/
  version: 2.0.15.RELEASE

build:
  - mvn compile assembly:single -q

files:
  - target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar

command: >
  java -jar target/benchmark-0.0.1-jar-with-dependencies.jar

