framework:
  website: micronaut.io
  version: 1.2

image: gradle:jdk8

build:
  - gradle build

files:
  - build/distributions/micronaut-0.1.tar

before_command:
  - tar -xvf build/distributions/micronaut-0.1.tar

command: micronaut-0.1/bin/micronaut
