framework:
  website: micronaut.io
  version: 1.2

image: gradle:jdk8-alpine

build:
  - gradle build --project-cache-dir ~/.gradle

patch:
  - USER root
  - RUN mkdir -p build/classes/java/main
  - RUN chown -R gradle build
  - USER gradle

files:
  - build/distributions/micronaut-0.1.tar

before_command:
  - tar -xvf build/distributions/micronaut-0.1.tar

command: micronaut-0.1/bin/micronaut
