framework:
  website: micronaut.io
  version: 1.2

image: gradle:6.3-jdk8

build:
  - gradle build --project-cache-dir ~/.gradle

patch:
  - USER root
  - RUN chown -R gradle /usr/src/app
  - USER gradle

files:
  - build/distributions/micronaut-0.1.tar

before_command:
  - tar -xvf build/distributions/micronaut-0.1.tar

command: micronaut-0.1/bin/micronaut
