framework:
  website: pakyow.com
  version: 1.0

bootstrap:
  - bundle config set without "development test"
  - bundle config set path "vendor/bundle"
  - bundle install
  - bundle binstubs pakyow-core
  - bundle binstubs bundler

command: bundle exec pakyow boot -e production
