providers:
  digitalocean:
    version: 3.6
    config:
      package_update: true
      package_upgrade: true
      packages:
        - python3
        - python3-dev
        - build-essential
      runcmd:
        - curl https://bootstrap.pypa.io/get-pip.py -o /tmp/setup.py
        - python3 /tmp/setup.py
        - rm -fr /tmp/setup.py
