[package]
name = "server"
version = "0.1.0"
authors = ["taicsuzu <taicsuzu@yahoo-corp.jp>"]

[dependencies]
iron = "~0.6"
router = "*"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
incremental = false
