framework:
  website: spring.io/projects/spring-boot
  version: 2.3

binaries:
  - target/benchmark-0.0.1-SNAPSHOT.jar

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/benchmark-0.0.1-SNAPSHOT.jar
