framework:
  github: chubbyphp/chubbyphp-framework
  version: 3.0

files:
  - composer.json
  - "**/*.php"
  - .rr.yaml

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  - vendor/bin/rr get-binary

command: /opt/web/rr serve
