language:
  version: 7.4

  engines:
    workerman:
      build_deps:
        - libevent-dev
      modules:
        - pcntl
        - posix
        - sockets
      extensions:
        - event
      extensions_fix:
        - rm -fr /usr/local/etc/php/conf.d/docker-php-ext-event.ini
        - echo 'extension=event.so' >> /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini
      command: php public/index.php start
    swoole:
      extensions:
        - swoole
      command: php public/index.php
    road-runner:
      bootstrap:
        - vendor/bin/rr get-binary
      command: ./rr serve
    php-fpm:
      deps:
        - nginx
    reactphp:
      files:
        - bin/console
      build_deps:
        - libevent-dev
      modules:
        - intl
        - pcntl
        - posix
        - sockets
      bootstrap:
        - mkdir -p var/cache && chmod 777 var/cache
        - mkdir -p var/log && chmod 777 var/log
      command: bin/console server:run 0.0.0.0:3000 --quiet

framework:
  engines:
    - php-fpm

  files:
    - "**/*.php"
    - composer.json
