framework:
  website: antidotfw.io
  github: antidot-framework/react-framework
  version: 0.2

build_deps:
  - libevent-dev

php_mod:
  - intl
  - pcntl
  - posix
  - sockets

before_command:
  - mkdir -p var/cache && chmod 777 var/cache

command: bin/console server:run --quiet
