framework:
  website: antidotfw.io
  github: antidot-framework/react-framework
  version: 0.2

  engines:
    reactphp:
      build_deps:
        - libevent-dev
      modules:
        - intl
        - pcntl
        - posix
        - sockets
      bootstrap:
        - mkdir -p var/cache && chmod 777 var/cache
        - mkdir -p var/log && chmod 777 var/log
      command: bin/console server:run --quiet
