framework:
  website: restheart.org
  version: 5.1.6

build:
  - mvn package

files:
  - restheart.yml

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/restheart-benchmarker.jar /opt/web/restheart.yml