framework:
  website: restheart.org
  version: 5.1

build:
  - mvn package

files:
  - restheart.yml

binaries:
  - target/benchmark.jar
  - restheart.yml

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/benchmark.jar /opt/web/restheart.yml