framework:
  website: jooby.io
  version: 2.8

build:
  - mvn clean package

binaries:
  - target/benchmark.jar

command: >
  java -benchmark
  -Xms4g -Xmx4g -XX:+UseNUMA -XX:+UseParallelGC -XX:-UseBiasedLocking -XX:+UseStringDeduplication
  -jar target/benchmark.jar benchmark.App
