framework:
  website: jooby.io
  version: 2.9

build:
  - mvn clean package

binaries:
  - target/benchmark.jar

command: >
  java -server
  -Xms4g -Xmx4g -XX:+UseNUMA -XX:+UseParallelGC -XX:-UseBiasedLocking -XX:+UseStringDeduplication
  -jar target/benchmark.jar benchmark.App
