framework:
  website: jooby.io
  version: 2.9

build:
  - mvn clean package

binaries:
  - target/server.jar

command: >
  /usr/bin/java -server
  -XX:+UseNUMA -XX:+UseParallelGC -XX:-UseBiasedLocking -XX:+UseStringDeduplication
  -jar target/benchmark.jar benchmark.App
