name: CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 0 0 * * 3
jobs:
  matrix:
    runs-on:	ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:  
          fetch-depth: 2
      - uses: actions/setup-ruby@v1
      - name: Install deps
        run: bundle install --jobs 4 --retry 3
      - id: set-matrix
        run: echo "::set-output name=matrix::$(bundle exec rake ci:matrix)"
        env:
          BASE_COMMIT: ${{ github.event.pull_request.base.sha }}
          LAST_COMMIT: ${{ github.event.pull_request.head.sha }}

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  test:
    needs: matrix

    runs-on: ubuntu-20.04
          
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: Install deps
        run: bundle install --jobs 4 --retry 3

      - name: Configure
        run: bundle exec rake config

      - name: Get docker version
        run: docker --version

      - name: Setup
        run: |
          cd ${{ matrix.directory }} 
          make build  -f .Makefile
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test
        run: bundle exec rspec .spec
        env:
          FRAMEWORK: ${{ matrix.framework }}