name: CI

on: [push, pull_request]

jobs:
    dynamic_matrix:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
        - 
            id: set-matrix
            run: echo "::set-output name=matrix::{\"include\":[{\"framework\":\"ruby/rails\",\"directory\":\"ruby/rails\"},{\"framework\":\"ruby/sinatra\",\"directory\":\"ruby/sinatra\"}]}"

        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    test_implementations:
        needs: dynamic_matrix

        runs-on: ubuntu-latest
        strategy:
            matrix: ${{fromJson(needs.dynamic_matrix.outputs.matrix)}}

        steps:
            - name: Test
              run: cd $DIRECTORY && make build  -f .Makefile && cd - && bundle exec rspec .spec