name: CI

on: [push, pull_request]

jobs:
    dynamic_matrix:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
        - 
            id: set-matrix
            run: echo "::set-output name=matrix::{\"include\":[{\"framework\":\"ruby/rails\",\"directory\":\"ruby/rails\"}]}"

        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

    test:
        needs: dynamic_matrix

        runs-on: ubuntu-latest
        strategy:
            matrix: ${{fromJson(needs.dynamic_matrix.outputs.matrix)}}

        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - uses: actions/setup-ruby@v1
            - run: bundle install
            - name: Create config
              run: bundle exec rake config
            - name: Build container
              run: cd $DIRECTORY && make build  -f .Makefile && cd -
              env:
                DIRECTORY: ${{ matrix.directory }}
            - name: Test
              run: bundle exec rspec .spec
              env:
                FRAMEWORK: ${{ matrix.framework }}